name: nuget build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    
  pull_request:
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download NiTiS Build Tools
        run: |
          cd ..
          git clone "https://github.com/NiTiS-Dev/NiTiS-Dev.github.io.git" "NiTiS-Site"
          cd NiTiS-Site/buildtools
          echo "NBT_HOME=$(pwd)" >> $GITHUB_ENV
          echo ---------------
          echo $NBT_HOME
          echo ---------------
          
          
      - name: Build
        run: |
          echo $NBT_HOME
          cd Source/
          dotnet clean
          dotnet restore
          dotnet pack -c Release -o ../.build/
          
      - name: Nuget Upload
        run: |
          cd .build/
          dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
